name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:      
    inputs:
      dry_run:
        required: true
        type: boolean      
  
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        pkg_root: [./Packages/ga.fuquna.prefsgui, ./Packages/ga.fuquna.prefsgui.rosettaui, ./Packages/ga.fuquna/prefsgui.rapidgui,]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19
        branch: ${{ github.ref_name }}
        working_directory: ${{ matrix.pkg_root }}  
        extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git
        extends: |
            semantic-release-monorepo@7.0.8
        dry_run: ${{ inputs.dry_run }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - run: sleep 60
